In [56]:
import pandas
df = pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [57]:
import geopy
from geopy.geocoders import Nominatim
nom = Nominatim(scheme = 'http')
n = nom.geocode("3995 23rd St, San Francisco, CA 94114")
n.latitude

37.7529648

In [34]:
n.longitude

-122.4317141

In [58]:
df["Address"] = df["Address"] + ", " + df["City"] + ", " + df["State"] + ", " + df["Country"]
df

,ID,Address,City,State,Country,Name,Employees
0,1,"3666 21st St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Madeira,8
1,2,"735 Dolores St, San Francisco, CA 94119, USA",San Francisco,CA 94119,USA,Bready Shop,15
2,3,"332 Hill St, San Francisco, California 94114, USA",San Francisco,California 94114,USA,Super River,25
3,4,"3995 23rd St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Ben's Shop,10
4,5,"1056 Sanchez St, San Francisco, California, USA",San Francisco,California,USA,Sanchez,12
5,6,"551 Alvarado St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Richvalley,20

In [59]:
df["Coordinates"] = df["Address"].apply(nom.geocode)
df

,ID,Address,City,State,Country,Name,Employees,Coordinates
0,1,"3666 21st St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Madeira,8,"(21st Street, Castro District, SF, California,..."
1,2,"735 Dolores St, San Francisco, CA 94119, USA",San Francisco,CA 94119,USA,Bready Shop,15,None
2,3,"332 Hill St, San Francisco, California 94114, USA",San Francisco,California 94114,USA,Super River,25,"(Hill Street, Liberty Street Historic District..."
3,4,"3995 23rd St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Ben's Shop,10,"(3995, 23rd Street, Noe Valley, SF, California..."
4,5,"1056 Sanchez St, San Francisco, California, USA",San Francisco,California,USA,Sanchez,12,"(Sanchez Street, Noe Valley, SF, California, 9..."
5,6,"551 Alvarado St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Richvalley,20,"(Alvarado Street, Noe Valley, SF, California, ..."

In [60]:
df["Latitude"] = df["Coordinates"].apply(lambda x: x.latitude if x != None else None)
df["Longitude"] = df["Coordinates"].apply(lambda x: x.longitude if x != None else None)
df

,ID,Address,City,State,Country,Name,Employees,Coordinates,Latitude,Longitude
0,1,"3666 21st St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Madeira,8,"(21st Street, Castro District, SF, California,...",37.755445,-122.438770
1,2,"735 Dolores St, San Francisco, CA 94119, USA",San Francisco,CA 94119,USA,Bready Shop,15,None,NaN,NaN
2,3,"332 Hill St, San Francisco, California 94114, USA",San Francisco,California 94114,USA,Super River,25,"(Hill Street, Liberty Street Historic District...",37.756102,-122.421041
3,4,"3995 23rd St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Ben's Shop,10,"(3995, 23rd Street, Noe Valley, SF, California...",37.752965,-122.431714
4,5,"1056 Sanchez St, San Francisco, California, USA",San Francisco,California,USA,Sanchez,12,"(Sanchez Street, Noe Valley, SF, California, 9...",37.748362,-122.429346
5,6,"551 Alvarado St, San Francisco, CA 94114, USA",San Francisco,CA 94114,USA,Richvalley,20,"(Alvarado Street, Noe Valley, SF, California, ...",37.753666,-122.434440